# Generated by Django 5.1.1 on 2024-10-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='desc',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
